apiVersion: v1
kind: Pod
metadata:
  name: "motorista-service"
  labels:
    app: "motorista-service"
spec:
  containers:
  - name: "motorista-service"
    image: "matheuspsilva29/motorista-service:1.0.0"
    ports:
    - containerPort: 8081