apiVersion: v1
kind: Service
metadata:
  name: db-frete
spec:
  selector:
    app: db-frete
  ports:
    - protocol: TCP
      port: 5432  # Porta do serviço dentro do cluster
      targetPort: 5432  # Porta do container do banco de dados
