apiVersion: v1
kind: Service
metadata:
  name: db-motorista
spec:
  selector:
    app: db-motorista
  ports:
    - protocol: TCP
      port: 5432  # Porta do serviço dentro do cluster
      targetPort: 5432  # Porta do container do db-motorista