apiVersion: v1
kind: Service
metadata:
  name: motorista-service
spec:
  selector:
    app: motorista-service
  ports:
    - protocol: TCP
      port: 8081  # Porta do serviço dentro do cluster
      targetPort: 8081  # Porta do container do motorista-service
  type: NodePort